# Cloudflare Pages Configuration for ThoughtFull Dreams
# For best results, use GitHub integration deployment
# This file is used for manual deployments via Wrangler

name = "thoughtfull-dreams"
compatibility_date = "2024-10-18"

# Note: For Next.js with dynamic routes, use GitHub integration
# Build output directory varies based on Next.js version
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "thoughtfull-dreams"

[env.production.vars]
# Environment variables for production
# Add these via Cloudflare Dashboard → Pages → Settings → Environment Variables
# NEXT_PUBLIC_SUPABASE_URL = "https://vnoyyctltxouigjyqvav.supabase.co"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-key"
# NEXT_PUBLIC_BASE_URL = "https://thoughtfull-dreams.pages.dev"

